// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"fabric_ebl/sal/dao/generator/model"
)

func newCompanyPO(db *gorm.DB, opts ...gen.DOOption) companyPO {
	_companyPO := companyPO{}

	_companyPO.companyPODo.UseDB(db, opts...)
	_companyPO.companyPODo.UseModel(&model.CompanyPO{})

	tableName := _companyPO.companyPODo.TableName()
	_companyPO.ALL = field.NewAsterisk(tableName)
	_companyPO.ID = field.NewInt64(tableName, "id")
	_companyPO.Name = field.NewString(tableName, "name")
	_companyPO.Code = field.NewString(tableName, "code")
	_companyPO.Type = field.NewInt64(tableName, "type")
	_companyPO.Seal = field.NewString(tableName, "seal")
	_companyPO.Balance = field.NewFloat64(tableName, "balance")
	_companyPO.Extra = field.NewString(tableName, "extra")
	_companyPO.CreatedAt = field.NewInt64(tableName, "created_at")
	_companyPO.UpdatedAt = field.NewInt64(tableName, "updated_at")
	_companyPO.DeletedAt = field.NewInt64(tableName, "deleted_at")

	_companyPO.fillFieldMap()

	return _companyPO
}

type companyPO struct {
	companyPODo

	ALL       field.Asterisk
	ID        field.Int64
	Name      field.String
	Code      field.String
	Type      field.Int64
	Seal      field.String
	Balance   field.Float64
	Extra     field.String
	CreatedAt field.Int64
	UpdatedAt field.Int64
	DeletedAt field.Int64

	fieldMap map[string]field.Expr
}

func (c companyPO) Table(newTableName string) *companyPO {
	c.companyPODo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c companyPO) As(alias string) *companyPO {
	c.companyPODo.DO = *(c.companyPODo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *companyPO) updateTableName(table string) *companyPO {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt64(table, "id")
	c.Name = field.NewString(table, "name")
	c.Code = field.NewString(table, "code")
	c.Type = field.NewInt64(table, "type")
	c.Seal = field.NewString(table, "seal")
	c.Balance = field.NewFloat64(table, "balance")
	c.Extra = field.NewString(table, "extra")
	c.CreatedAt = field.NewInt64(table, "created_at")
	c.UpdatedAt = field.NewInt64(table, "updated_at")
	c.DeletedAt = field.NewInt64(table, "deleted_at")

	c.fillFieldMap()

	return c
}

func (c *companyPO) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *companyPO) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 10)
	c.fieldMap["id"] = c.ID
	c.fieldMap["name"] = c.Name
	c.fieldMap["code"] = c.Code
	c.fieldMap["type"] = c.Type
	c.fieldMap["seal"] = c.Seal
	c.fieldMap["balance"] = c.Balance
	c.fieldMap["extra"] = c.Extra
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
	c.fieldMap["deleted_at"] = c.DeletedAt
}

func (c companyPO) clone(db *gorm.DB) companyPO {
	c.companyPODo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c companyPO) replaceDB(db *gorm.DB) companyPO {
	c.companyPODo.ReplaceDB(db)
	return c
}

type companyPODo struct{ gen.DO }

type ICompanyPODo interface {
	gen.SubQuery
	Debug() ICompanyPODo
	WithContext(ctx context.Context) ICompanyPODo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICompanyPODo
	WriteDB() ICompanyPODo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICompanyPODo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICompanyPODo
	Not(conds ...gen.Condition) ICompanyPODo
	Or(conds ...gen.Condition) ICompanyPODo
	Select(conds ...field.Expr) ICompanyPODo
	Where(conds ...gen.Condition) ICompanyPODo
	Order(conds ...field.Expr) ICompanyPODo
	Distinct(cols ...field.Expr) ICompanyPODo
	Omit(cols ...field.Expr) ICompanyPODo
	Join(table schema.Tabler, on ...field.Expr) ICompanyPODo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICompanyPODo
	RightJoin(table schema.Tabler, on ...field.Expr) ICompanyPODo
	Group(cols ...field.Expr) ICompanyPODo
	Having(conds ...gen.Condition) ICompanyPODo
	Limit(limit int) ICompanyPODo
	Offset(offset int) ICompanyPODo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICompanyPODo
	Unscoped() ICompanyPODo
	Create(values ...*model.CompanyPO) error
	CreateInBatches(values []*model.CompanyPO, batchSize int) error
	Save(values ...*model.CompanyPO) error
	First() (*model.CompanyPO, error)
	Take() (*model.CompanyPO, error)
	Last() (*model.CompanyPO, error)
	Find() ([]*model.CompanyPO, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CompanyPO, err error)
	FindInBatches(result *[]*model.CompanyPO, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.CompanyPO) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICompanyPODo
	Assign(attrs ...field.AssignExpr) ICompanyPODo
	Joins(fields ...field.RelationField) ICompanyPODo
	Preload(fields ...field.RelationField) ICompanyPODo
	FirstOrInit() (*model.CompanyPO, error)
	FirstOrCreate() (*model.CompanyPO, error)
	FindByPage(offset int, limit int) (result []*model.CompanyPO, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICompanyPODo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c companyPODo) Debug() ICompanyPODo {
	return c.withDO(c.DO.Debug())
}

func (c companyPODo) WithContext(ctx context.Context) ICompanyPODo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c companyPODo) ReadDB() ICompanyPODo {
	return c.Clauses(dbresolver.Read)
}

func (c companyPODo) WriteDB() ICompanyPODo {
	return c.Clauses(dbresolver.Write)
}

func (c companyPODo) Session(config *gorm.Session) ICompanyPODo {
	return c.withDO(c.DO.Session(config))
}

func (c companyPODo) Clauses(conds ...clause.Expression) ICompanyPODo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c companyPODo) Returning(value interface{}, columns ...string) ICompanyPODo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c companyPODo) Not(conds ...gen.Condition) ICompanyPODo {
	return c.withDO(c.DO.Not(conds...))
}

func (c companyPODo) Or(conds ...gen.Condition) ICompanyPODo {
	return c.withDO(c.DO.Or(conds...))
}

func (c companyPODo) Select(conds ...field.Expr) ICompanyPODo {
	return c.withDO(c.DO.Select(conds...))
}

func (c companyPODo) Where(conds ...gen.Condition) ICompanyPODo {
	return c.withDO(c.DO.Where(conds...))
}

func (c companyPODo) Order(conds ...field.Expr) ICompanyPODo {
	return c.withDO(c.DO.Order(conds...))
}

func (c companyPODo) Distinct(cols ...field.Expr) ICompanyPODo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c companyPODo) Omit(cols ...field.Expr) ICompanyPODo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c companyPODo) Join(table schema.Tabler, on ...field.Expr) ICompanyPODo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c companyPODo) LeftJoin(table schema.Tabler, on ...field.Expr) ICompanyPODo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c companyPODo) RightJoin(table schema.Tabler, on ...field.Expr) ICompanyPODo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c companyPODo) Group(cols ...field.Expr) ICompanyPODo {
	return c.withDO(c.DO.Group(cols...))
}

func (c companyPODo) Having(conds ...gen.Condition) ICompanyPODo {
	return c.withDO(c.DO.Having(conds...))
}

func (c companyPODo) Limit(limit int) ICompanyPODo {
	return c.withDO(c.DO.Limit(limit))
}

func (c companyPODo) Offset(offset int) ICompanyPODo {
	return c.withDO(c.DO.Offset(offset))
}

func (c companyPODo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICompanyPODo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c companyPODo) Unscoped() ICompanyPODo {
	return c.withDO(c.DO.Unscoped())
}

func (c companyPODo) Create(values ...*model.CompanyPO) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c companyPODo) CreateInBatches(values []*model.CompanyPO, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c companyPODo) Save(values ...*model.CompanyPO) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c companyPODo) First() (*model.CompanyPO, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CompanyPO), nil
	}
}

func (c companyPODo) Take() (*model.CompanyPO, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CompanyPO), nil
	}
}

func (c companyPODo) Last() (*model.CompanyPO, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CompanyPO), nil
	}
}

func (c companyPODo) Find() ([]*model.CompanyPO, error) {
	result, err := c.DO.Find()
	return result.([]*model.CompanyPO), err
}

func (c companyPODo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CompanyPO, err error) {
	buf := make([]*model.CompanyPO, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c companyPODo) FindInBatches(result *[]*model.CompanyPO, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c companyPODo) Attrs(attrs ...field.AssignExpr) ICompanyPODo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c companyPODo) Assign(attrs ...field.AssignExpr) ICompanyPODo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c companyPODo) Joins(fields ...field.RelationField) ICompanyPODo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c companyPODo) Preload(fields ...field.RelationField) ICompanyPODo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c companyPODo) FirstOrInit() (*model.CompanyPO, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CompanyPO), nil
	}
}

func (c companyPODo) FirstOrCreate() (*model.CompanyPO, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CompanyPO), nil
	}
}

func (c companyPODo) FindByPage(offset int, limit int) (result []*model.CompanyPO, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c companyPODo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c companyPODo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c companyPODo) Delete(models ...*model.CompanyPO) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *companyPODo) withDO(do gen.Dao) *companyPODo {
	c.DO = *do.(*gen.DO)
	return c
}
