// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCompanyPO = "companys"

// CompanyPO mapped from table <companys>
type CompanyPO struct {
	ID        int64   `gorm:"column:id;primaryKey" json:"id"`
	Name      string  `gorm:"column:name;not null" json:"name"`
	Code      string  `gorm:"column:code;not null" json:"code"`
	Type      int64   `gorm:"column:type;not null" json:"type"`
	Seal      *[]byte `gorm:"column:seal" json:"seal"`
	Balance   float64 `gorm:"column:balance;not null" json:"balance"`
	Extra     *string `gorm:"column:extra" json:"extra"`
	CreatedAt int64   `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt int64   `gorm:"column:updated_at;not null" json:"updated_at"`
	DeletedAt *int64  `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName CompanyPO's table name
func (*CompanyPO) TableName() string {
	return TableNameCompanyPO
}
