// Code generated by hertz generator.

package model

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _signupMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _companyMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createcompanyMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcompanyalllistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _eblMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createeblMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryallebllistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryebllistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _submiteblMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _operateeblMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sealMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadsealMw() []app.HandlerFunc {
	// your code...
	return nil
}
